[package]
name = "markon"
version = "0.2.0"
edition = "2021"
authors = ["kookyleo"]
description = "A lightweight Markdown renderer with GitHub styling and Medium-like annotations"
license = "Apache-2.0"
repository = "https://github.com/kookyleo/markon"
homepage = "https://github.com/kookyleo/markon"
keywords = ["markdown", "preview", "github", "mermaid", "toc"]
categories = ["command-line-utilities", "text-processing", "web-programming"]
readme = "README.md"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
axum = "0.7.5"
tokio = { version = "1.39.2", features = ["full"] }
pulldown-cmark = "0.11.0"
syntect = "5.2.0"
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "8.7.2"
tera = "1.20.0"
emojis = "0.7.2"
regex = "1.12.2"
lazy_static = "1.5.0"
html-escape = "0.2.13"
urlencoding = "2.1.3"
