[package]
name = "markon"
version = "0.5.0"
edition = "2021"
authors = ["kookyleo"]
description = "A lightweight Markdown renderer with GitHub styling and Medium-like annotations"
license = "Apache-2.0"
repository = "https://github.com/kookyleo/markon"
homepage = "https://github.com/kookyleo/markon"
keywords = ["markdown", "preview", "github", "mermaid", "toc"]
categories = ["command-line-utilities", "text-processing", "web-programming"]
readme = "README.md"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
axum = { version = "0.8.6", features = ["ws"] }
futures-util = "0.3.31"
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1"
log = "0.4.28"
uuid = { version = "1.18.1", features = ["v4"] }
pulldown-cmark = "0.13.0"
syntect = "5.3.0"
tower-http = { version = "0.6.6", features = ["fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "8.8.0"
tera = "1.20.0"
emojis = "0.7.2"
regex = "1.12.2"
lazy_static = "1.5.0"
html-escape = "0.2.13"
urlencoding = "2.1.3"
qr2term = "0.3.3"
qrcode = "0.14.1"
open = "5.3.2"
rusqlite = { version = "0.37.0", features = ["bundled"] }
dirs = "6.0.0"
