[package]
name = "markon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
axum = "0.7.5"
tokio = { version = "1.39.2", features = ["full"] }
pulldown-cmark = "0.11.0"
syntect = "5.2.0"
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "8.7.2"
tera = "1.20.0"
emojis = "0.7.2"
regex = "1.12.2"
lazy_static = "1.5.0"
html-escape = "0.2.13"
urlencoding = "2.1.3"
